[package]
name = "ain-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.12.1"
libsecp256k1 = "0.7.1"
sha3 = "0.10.6"
hex = "0.4.3"
hex-literal = "0.3.4"

