# Existing labels to be refactored or removed entirely.
- color: ffffff
  name: bug
  description: Something isn't working
- color: ffffff
  name: consensus
  description: Consensus breaking updates
- color: ffffff
  name: documentation
  description: Improvements or additions to documentation
- color: ffffff
  name: enhancement
  description: New feature or request
- color: ffffff
  name: epic
  description:
- color: ffffff
  name: help wanted
  description: Extra attention is needed
- color: ffffff
  name: invalid
  description: This doesn't seem right
- color: ffffff
  name: minor
  description: Minor changes
- color: ffffff
  name: question
  description: Further information is requested
- color: ffffff
  name: stale
  description:
- color: ffffff
  name: wip
  description:

# GitHub generic useful labels
- color: c4d471
  name: duplicate
  description: This issue or pull request already exists
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: ffffff
  name: wontfix
  description: This will not be worked on

# Kind
- color: e7e9eb
  name: kind/feature
  description: New feature request
- color: e7e9eb
  name: kind/fix
  description: Fix a bug
- color: e7e9eb
  name: kind/docs
  description: Non feature documentation change
- color: e7e9eb
  name: kind/refactor
  description: Non feature refactor change
- color: e7e9eb
  name: kind/chore
  description: Non feature change

# Area (for PRs)
- color: fbca04
  name: area/consensus
- color: fbca04
  name: area/feature
- color: fbca04
  name: area/optimisation
- color: fbca04
  name: area/workflow

# Priority
- color: f79489
  name: P1
- color: f8afa6
  name: P2
- color: fadcd9
  name: P3
- color: f9f1f0
  name: P4

# Effort
- color: 34a0a4
  name: E1
- color: 52b69a
  name: E2
- color: 99d98c
  name: E3
- color: b5e48c
  name: E4
