name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/fix'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/refactor'
      - 'kind/chore'
      - 'kind/docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  minor:
    labels:
      - 'kind/feature'
  patch:
    labels:
      - 'kind/refactor'
      - 'kind/chore'
      - 'kind/docs'
      - 'kind/fix'
  default: patch
template: |
  ## What’s Changed

  $CHANGES

  ## How to run?

  Download and untar the relevant version to your operating system, run `bin/defid` or `bin/defid.exe` to start a DeFi Blockchain daemon. The client (CLI) can be found at `bin/defi-cli` or `bin/defi-cli.exe`.

  ### DeFi App (GUI) users

  If you are running the [desktop DeFi App](https://github.com/defich/app), you do not have to manually update the underlying node as the app will handle it. Check https://github.com/DeFiCh/app/releases for the latest releases.

  ## Issues

  Please report any issues to engineering@defichain.com, or reach out to is via [Telegram](https://t.me/defiblockchain) or [Reddit](https://reddit.com/r/defiblockchain).
