task:
  name: "FreeBsd 12.0 amd64  [GOAL: install]  [no depends, only system libs]"
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    CONFIGURE_OPTS: "--disable-dependency-tracking"
    GOAL: "install"
    CCACHE_SIZE: "200M"
    CCACHE_COMPRESS: 1
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - pkg install -y autoconf automake boost-libs git gmake libevent libtool openssl pkgconf python3 ccache
    - ./contrib/install_db4.sh $(pwd)
    - ccache --max-size=${CCACHE_SIZE}
  configure_script:
    - ./autogen.sh
    - ./configure ${CONFIGURE_OPTS} BDB_LIBS="-L$(pwd)/db4/lib -ldb_cxx-4.8" BDB_CFLAGS="-I$(pwd)/db4/include" || ( cat config.log && false)
  make_script:
    - gmake ${MAKEJOBS} ${GOAL} || ( echo "Build failure. Verbose build follows." && gmake ${GOAL} V=1 ; false )
  check_script:
    - gmake check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - ./test/functional/test_runner.py --jobs 9 --ci --extended --exclude feature_dbcrash --combinedlogslen=1000 --quiet --failfast
task:
  name: "x86_64 Linux  [GOAL: install]  [bionic]  [Using ./ci/ system]"
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  depends_built_cache:
    folder: "/tmp/cirrus-ci-build/depends/built"
  depends_sdk_cache:
    folder: "/tmp/cirrus-ci-build/depends/sdk-sources"
  install_script:
    - apt-get update
    - apt-get -y install git bash ccache
    - ccache --max-size=${CCACHE_SIZE}
  ci_script:
    - ./ci/test_run_all.sh
