#pragma once
#include <libain_grpc.h>

void Eth_Accounts(EthAccountsResult& result);
void Eth_Call(EthCallInput& request, EthCallResult& result);
void Eth_Sign(EthSignInput& request, EthSignResult& result);
void Eth_GetBalance(EthGetBalanceInput& request, EthGetBalanceResult& result);
void Eth_SendTransaction(EthSendTransactionInput& request, EthSendTransactionResult& result);
void Eth_CoinBase(EthCoinBaseResult& result);
void Eth_MiningResult(EthMiningResult& result);
void Eth_HashRate(EthHashRateResult& result);
void Eth_GasPrice(EthGasPriceResult& result);
void Eth_BlockNumber(EthBlockNumberResult& result);
void Eth_GetTransactionCount(EthGetTransactionCountInput& request, EthGetTransactionCountResult& result);
void Eth_GetBlockCountByHash(EthGetBlockTransactionCountByHashInput& request, EthGetBlockTransactionCountByHashResult& result);
void Eth_GetBlockTransactionCountByNumber(EthGetBlockTransactionCountByNumberInput& request, EthGetBlockTransactionCountByNumberResult& result);
void Eth_GetUncleCountByBlockHash(EthGetUncleCountByBlockHashInput& request, EthGetUncleCountByBlockHashResult& result);
void Eth_GetUncleCountByBlockNumber(EthGetUncleCountByBlockNumberInput& request, EthGetUncleCountByBlockNumberResult& result);
void Eth_GetCode(EthGetCodeInput& request, EthGetCodeResult& result);
void Eth_SignTransaction(EthSignTransactionInput& request, EthSignTransactionResult& result);
void Eth_SendRawTransaction(EthSendRawTransactionInput& request, EthSendRawTransactionResult& result);
void Eth_EstimateGas(EthEstimateGasInput& request, EthEstimateGasResult& result);
void Eth_GetBlockByHash(EthGetBlockByHashInput& request, EthGetBlockByHashResult& result);
void Eth_GetBlockByNumber(EthGetBlockByNumberInput& request, EthGetBlockByNumberResult& result);
void Eth_GetTransactionByHash(EthGetTransactionByHashInput& request, EthGetTransactionByHashResult& result);
void Eth_GetTransactionByBlockHashAndIndex(EthGetTransactionByBlockHashAndIndexInput& request, EthGetTransactionByBlockHashAndIndexResult& result);
void Eth_GetTransactionByBlockNumberAndIndex(EthGetTransactionByBlockNumberAndIndexInput& request, EthGetTransactionByBlockNumberAndIndexResult& result);
void Eth_GetUncleByBlockHashAndIndex(EthGetUncleByBlockHashAndIndexInput& request, EthGetUncleByBlockHashAndIndexResult& result);
void Eth_GetUncleByBlockNumberAndIndex(EthGetUncleByBlockNumberAndIndexInput& request, EthGetUncleByBlockNumberAndIndexResult& result);
void Eth_GetCompilers(EthGetCompilersResult& result);
void Eth_CompileSolidity(EthCompileSolidityInput& request, EthCompileSolidityResult& result);
void Eth_CompileLll(EthCompileLllInput& request, EthCompileLllResult& result);
void Eth_CompileSerpent(EthCompileSerpentInput& request, EthCompileSerpentResult& result);
void Eth_ProtocolVersion(EthProtocolVersionResult& result);
void Eth_Web3Sha3(Web3Sha3Input& request, Web3Sha3Result& result);
void Eth_NetPeerCount(NetPeerCountResult& result);
void Eth_NetVersion(NetVersionResult& result);
void Eth_Web3ClientVersion(Web3ClientVersionResult& result);
void Eth_GetWork(EthGetWorkResult& result);
void Eth_SubmitWork(EthSubmitWorkInput& request, EthSubmitWorkResult& result);
void Eth_SubmitHashRate(EthSubmitHashrateInput& request, EthSubmitHashrateResult& result);
void Eth_GetStorageAt(EthGetStorageAtInput& request, EthGetStorageAtResult& result);
void Eth_GetTransactionReceipt(EthGetTransactionReceiptInput& request, EthGetTransactionReceiptResult& result);
void Eth_Syncing(EthSyncingResult& result);
void GetBestBlockHash(BlockResult& result);
