contact_links:
  - name: Telegram
    url: https://t.me/defiblockchain
    about: DeFiChain community on Telegram

  - name: Reddit
    url: https://reddit.com/r/defiblockchain
    about: DeFiChain community on Reddit
