.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. defi_qt test_defi_qt
clean: FORCE
	$(MAKE) -C .. defi_qt_clean test_defi_qt_clean
check: FORCE
	$(MAKE) -C .. test_defi_qt_check
defi-qt defi-qt.exe: FORCE
	 $(MAKE) -C .. defi_qt
