on:
  push:
    branches:
      - staging
      - develop
      - master
      - ci/*
  pull_request:
    branches:
      - staging
      - develop
      - master
      - ci/*
jobs:
  build-x86_64-linux-gnu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build and package
      run: ./make.sh docker-build-deploy-git
    - name: Publish artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: defichain-x86_64-pc-linux-gnu
        path: ./build/defichain-*
