name: Full Sync Tip Tests
on:
  pull_request:
    branches:
      - master
    types: [labeled, opened, reopened, synchronize]

jobs:
  build-binaries:
    if: contains(github.event.pull_request.labels.*.name, 'ci/sync-tip')
    runs-on: [self-hosted, linux, x64,server-2]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: defibins
        path: |
         src/defid
         src/defi-cli
    - name: Archive Binaries
      uses: actions/upload-artifact@v3
      with:
        name: defibins
        path: |
          src/defid
          src/defi-cli
    - name: Archive Shell Commands
      uses: actions/upload-artifact@v3
      with:
        name: sync
        path: |
          ci/parallel_sync/sync_then_diff.sh
    - name: Archive Sync to Tip Shell Command
      uses: actions/upload-artifact@v3
      with:
        name: sync-to-tip
        path: |
          ci/parallel_sync/sync_to_tip.sh

  sync:
    strategy:
      matrix:
        datadir:
         - start: 1900000
           stop: 1950000
         - start: 1950000
           stop: 2000000
         - start: 2000000
           stop: 2050000
         - start: 2050000
           stop: 2100000
         - start: 2100000
           stop: 2150000
         - start: 2150000
           stop: 2232254

    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    if: contains(github.event.pull_request.labels.*.name, 'ci/sync-tip')
    continue-on-error: true
    container:
      image : gcr.io/br-blockchains-dev/datadir-${{matrix.datadir.start}}
      options: --privileged
      env:
        START_BLOCK: ${{matrix.datadir.start}}
        STOP_BLOCK: ${{matrix.datadir.stop}}
        DEFID_BIN: ./defid
        DEFI_CLI_BIN: ./defi-cli
    timeout-minutes: 4320
    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: defibins
    - name: Download Shell Commands
      uses: actions/download-artifact@v3
      with:
        name: sync
    - name: Set Permissions
      run: |
        chmod 777 defid
        chmod 777 defi-cli
        chmod 777 sync_then_diff.sh
    - name: Sync and Diff
      run: ./sync_then_diff.sh
    - name: Show Debug Log
      run: cat $DATADIR/debug.log
      if: ${{ failure() ||  success() }}
  sync-to-tip:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    if: contains(github.event.pull_request.labels.*.name, 'ci/sync-tip')
    continue-on-error: true
    container:
      image : gcr.io/br-blockchains-dev/datadir-${{matrix.datadir.start}}
      options: --privileged
      env:
        START_BLOCK: 2150000
        STOP_BLOCK: 2232254
        DEFID_BIN: ./defid
        DEFI_CLI_BIN: ./defi-cli
    timeout-minutes: 4320
    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: defibins
    - name: Download Shell Commands
      uses: actions/download-artifact@v3
      with:
        name: sync-to-tip
    - name: Set Permissions
      run: |
        chmod 777 defid
        chmod 777 defi-cli
        chmod 777 sync_to_tip.sh
    - name: Sync to Tip
      run: ./sync_to_tip.sh
    - name: Show Debug Log
      run: cat $DATADIR/debug.log
      if: ${{ failure() ||  success() }}
