name: Governance

on:
  pull_request:
    types: [ opened ]

jobs:
  main:
    name: DeFi Products
    runs-on: ubuntu-latest
    if: github.event.sender.type == 'User' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          script: |
            github.projects.createCard({
              column_id: 14429696,
              content_id: context.payload.pull_request.id,
              content_type: 'PullRequest',
            });

            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.sender.login]
            })
