name: Governance

on:
  issues:
    types: [ opened, labeled ]

jobs:
  main:
    name: DeFi Products
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'triage/accepted')
    steps:
      - uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          script: |
            github.projects.createCard({
              column_id: 13975681,
              content_id: context.payload.issue.id,
              content_type: 'Issue',
            })
