name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            artifact_name: build/defichain-x86_64-pc-linux-gnu-*.tar.gz
            asset_name: defichain-x86_64-pc-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - name: Build and package
      run: ./make.sh docker-release-git
    - name: Upload release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
