name: Sync labels

on:
  push:
    branches: [ master ]
    paths:
      - .github/labels.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - uses: micnncim/action-label-syncer@0e9c5104859d0e78219af63791636eba42382b5d
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
